development:
  adapter: postgresql
  encoding: unicode
  database: star_team_development
  host: localhost
  pool: 5
  username: audunn
  password: x72uidgsk

test:
  adapter: postgresql
  encoding: unicode
  database: star_team_test
  host: localhost
  pool: 5
  username: audunn
  password: x72uidgsk

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: star_team_production
#   pool: 5
#   username: audunn
#   password: x72uidgsk