# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3e6f64ce5d8787e74e63451ffaf21a6f3469ae25447961eacb2f043f3ef214d71d5cec21438032857f76411689e7d933338b732e7e094eb4e01d95c1b636b55

test:
  secret_key_base: 058a16cf389a12d448a93a469b1013d0b5171311d17f9014650a50332df0ff81e7f6f12d97bd3f262266574860fc78c7a1f302b75fabd87d7f622e0ef1bc16bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
